services:
  backend:
    build: 
      context: ./barbershop
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./barbershop:/app
    command: >
      sh -c "python manage.py makemigrations &&
             python manage.py makemigrations bookings &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    environment:
      - DEBUG=1

  frontend:
    image: nginx:alpine
    ports:
      - "5500:80"
    volumes:
      - ./client:/usr/share/nginx/html
    depends_on:
      - backend